# Generated by Django 3.2.15 on 2024-07-31 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='foodcartapp.restaurant', verbose_name='Ресторан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('01_created', 'Необработанный'), ('02_cooking', 'Готовится'), ('03_delivering', 'Доставляется'), ('04_completed', 'Доставлен')], db_index=True, default='created', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
