# Generated by Django 3.2.15 on 2024-08-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_auto_20240731_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('01_created', 'Необработанный'), ('02_cooking', 'Готовится'), ('03_delivering', 'Доставляется'), ('04_completed', 'Доставлен')], db_index=True, default='01_created', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
